<Project>
  <ItemGroup>
    <!-- The default profile of the MSTest.SDK already included the code coverage package,
       which does not seem to get updated when the MSTest.SDK package gets updated.
       This results in a warning about the old version of newtonsoft.json.
       The following line does not update the code coverage package in the release folder
    -->
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.7.0" />
  </ItemGroup>
</Project>
